[tool.poetry]
name = "matchescu-comparison-space-generation"
version = "0.8.8"
description = ""
authors = ["Andrei Olar <andrei.olar@samlex.ro>"]
readme = "README.md"
packages = [{include = "matchescu", from="src"}]

[tool.poetry.dependencies]
python = "!=3.14.1,~3.13"
matchescu-base = "^0.27.7"
matchescu-reference-store = "^0.9.9"
stopwords = "^1.0.2"
scikit-learn = "^1.9.0"
numpy = "^2.5.2"
datasketch = "^1.10.0"
polars = "^1.44.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
mypy = "^1.20.2"
ruff = "^0.16.5"
black = "^25.12.0"
matchescu-reference-extraction = "^0.9.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
